# Generated by Django 2.2.5 on 2019-11-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='wish',
            name='wish',
            field=models.CharField(max_length=100),
        ),
    ]
